apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: nginx
    tier: frontend
spec:
  containers:
  - name: my-container
    image: nginx
    resources:
      limits:
        cpu: "500m"        # Set CPU limit to 500 milliCPU
        memory: "512Mi"    # Set memory limit to 512 Mebibytes