apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp-custom-label
    type: front-end

spec:
  template:
    metadata:
      name: my-pod
      labels:
        app: myapp-custom-label
        type: front-end
    spec:
      containers:
      - name: my-nginx-container
        image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: front-end