# apiVersion: v1
# kind: Service                             # Defines to create Service type Object
# metadata:
#   name: demoservice
# spec:
#   ports:
#     - port: 80                               # Containers port exposed
#       targetPort: 80                     # Pods port
#   selector:
#     name: deployment-custom-label                    # Apply this service to any pods which has the specific label
#   type: NodePort                       # Specifies the service type i.e ClusterIP or NodePort


apiVersion: v1
kind: Service
metadata:
  name: my-nginx-demo-service
spec:
  selector:
    name: deployment-custom-label
  type: LoadBalancer
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 80
      nodePort: 30080